# Generated by Django 5.1.2 on 2024-10-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'todo_Todo',
            },
        ),
    ]
